Выполнил первое задание
htmlacademy-htmlcss/521207-device-32 pull request #1
Opened 2021-09-22 10:53 UTC by ilyakeps

2021-09-22 17:15 UTC, lawejr requested changes

2021-09-22 17:15 UTC, lawejr commented on Readme.md
> +* Наставник: [Александр Калинин](https://htmlacademy.ru/profile/id311377).
Отлично:) теперь давай потренируемся вносить правки, на случай, если будут какие-то реальные ошибки.
Замени ссылку наставника академии на ссылку моего профиля на GitHub.

2021-09-23 08:53 UTC, ilyakeps commented
Обновил ссылку наставника, теперь там профиль из GitHub

2021-09-23 09:06 UTC, lawejr approved these changes

2021-09-23 09:09 UTC, lawejr commented
👍Молодец, что пишешь содержательные и понятные сообщения в коммитах. Это тебе пригодится в будущем, если потребуется найти и исправить изменения, которые были сделаны ранее. Так же это поможет другим разработчикам разобраться в твоём коде, если потребуется.

2021-09-23 09:09 UTC, merged